from aws_cdk import Duration

#cloudwatch log configs
ECS_CW_LOG_GROUP_NAME="Todoozie-group"
ECS_CW_LOG_DB_STREAM_PREFIX="db-container-logs"
ECS_CW_LOG_APP_STREAM_PREFIX="db-container-logs"

#iam role
TASK_ROLE_NAME = "Todoozie-ecs-task-role"
TASK_EXECUTION_ROLE_NAME = "Todoozie-ecs-execution-role"
TASK_ROLE_SERVICE_PRINCIPAL="ecs-tasks.amazonaws.com"
TASK_ROLE_MANAGED_POLICY_NAME="CloudWatchLogsFullAccess"
EXECUTION_ROLE_SERVICE_PRINCIPAL="ecs-tasks.amazonaws.com"
EXECUTION_ROLE_MANAGED_POLICY_NAME_1="CloudWatchLogsFullAccess"
EXECUTION_ROLE_MANAGED_POLICY_NAME_2="service-role/AmazonECSTaskExecutionRolePolicy"

#ecr configs
ECR_IMAGE_TAG="cc2eeadf822955889a7732ea50716f857456d502"
ECS_SERVICE_SG_NAME="todoozieecsservicesg"

#alb configs
ALB_HEALTH_CHECK_PORT = "8000"
ALB_HEALTH_CHECK_PATH = "/docs"
ALB_HEALTH_CHECK_UNHEALTHY_THRESHOLD_COUNT = 10
ALB_HEALTH_CHECK_INTERVAL = Duration.seconds(120)
ALB_LISTENER_PORT=80
ALB_PRIVATE_SUBNET_STRING="PRIVATE_WITH_NAT"

#db container configs
DB_CONTAINER_HEALTH_CHECK_COMMAND=["CMD-SHELL", "pg_isready"]
DB_CONTAINER_HEALTH_CHECK_INTERVAL=Duration.seconds(20)
DB_CONTAINER_HEALTH_CHECK_TIMEOUT=Duration.seconds(5)
DB_CONTAINER_HEALTH_RETRY=5
DB_CONTAINER_HEALTH_ENVIRONMENT_VARIABLES={ "POSTGRES_PASSWORD": "admin", "POSTGRES_DB": "todoozie_db"}
DB_CONTAINER_PORT=5432
DB_CONTAINER_HOST_PORT=5432
DB_CONTAINER_NAME="DB"
DB_CONTAINER_IMAGE="postgres:13.6"

#App container configs
APP_CONTAINER_NAME="App"
APP_CONTAINER_HEALTH_ENVIRONMENT_VARIABLES={ "SECRET_KEY": "77b070105b32e1b78c3b16374702a634ca1349e966e2c9e4cede09154a0e048f", "DB_PASSWORD": "admin"}
APP_CONTAINER_PORT=8000
APP_CONTAINER_HOST_PORT=8000

#ecs configs
CLUSTER_NAME = "Todoozie-cluster"
ECS_TASK_DEF_CPU = 256
ECS_SERVICE_CPU = 512
ECS_SERVICE_MEMORY = 1024
ECS_SERVICE_HEALTH_CHECK_GRACE_PERIOD=Duration.seconds(300)
ECS_SERVICE_DESIRED_COUNT=1